
export const EXPERIENCE_LEVEL_GUIDE = Object.freeze({
  entry: { label: 'Entry', years: '0–1 years' },
  junior: { label: 'Junior', years: '1–3 years' },
  mid: { label: 'Mid', years: '4–7 years' },
  senior: { label: 'Senior', years: '8+ years' },
});

export const DEMO_TALENTS = Object.freeze([
  {
    experienceLevel: 'entry',
    firstName: 'Chidinma',
    lastName: 'Okafor',
    gender: 'female',
    dateOfBirth: '2003-03-14',
    phoneNumber: '+234 800 000 0001',
    location: 'Yaba, Lagos',
    jobTitle: 'Accounts Assistant',
    availability: 'immediate',
    education: 'BSc Accounting, University of Lagos (2025), Second Class Upper. NYSC discharge certificate obtained 2026.',
    skills: ['Bookkeeping', 'Microsoft Excel', 'QuickBooks', 'Financial Reporting', 'Accounts Payable'],
    certifications: ['ICAN Foundation Level — Passed', 'Microsoft Office Specialist: Excel Associate'],
    workExperience:
      'Completed a six-month internship in the accounts department of a Lagos-based distribution company, where I reconciled supplier statements, posted daily journal entries and prepared monthly petty-cash reports. Supported the finance team during year-end stock count and audit preparation. Volunteered as treasurer of the university accounting students\' association.',
  },
  {
    experienceLevel: 'entry',
    firstName: 'Tunde',
    lastName: 'Balogun',
    gender: 'male',
    dateOfBirth: '2002-08-21',
    phoneNumber: '+234 800 000 0002',
    location: 'Ibadan, Oyo',
    jobTitle: 'Frontend Developer',
    availability: 'immediate',
    education: 'BSc Computer Science, University of Ibadan (2025), Second Class Upper. NYSC service completed 2026.',
    skills: ['JavaScript', 'React', 'HTML & CSS', 'Git & GitHub', 'REST APIs', 'Node.js'],
    certifications: [
      'freeCodeCamp — Responsive Web Design',
      'Meta Front-End Developer Professional Certificate (Coursera)',
    ],
    workExperience:
      'Built and shipped three portfolio projects, including a school-fees tracker used by a local secondary school. Completed a four-month frontend internship at an Ibadan software studio, contributing React components and fixing UI bugs under senior review. Active in a campus developer community, running weekly Git and JavaScript workshops.',
  },
  {
    experienceLevel: 'entry',
    firstName: 'Aisha',
    lastName: 'Bello',
    gender: 'female',
    dateOfBirth: '2003-11-02',
    phoneNumber: '+234 800 000 0003',
    location: 'Kano, Kano',
    jobTitle: 'Content & Social Media Associate',
    availability: 'two_weeks',
    education: 'BSc Mass Communication, Bayero University Kano (2025), Second Class Upper.',
    skills: ['Content Writing', 'Copywriting', 'Social Media Management', 'Canva', 'Video Editing', 'Community Management'],
    certifications: [
      'HubSpot Content Marketing Certification',
      'Google Digital Garage — Fundamentals of Digital Marketing',
    ],
    workExperience:
      'Managed the social media pages of a campus radio station, growing its Instagram following from 1,200 to 6,500 in eight months. Wrote weekly features and scripts for on-air programmes, and completed a three-month content internship with a Kano fashion retailer producing product copy and short-form video.',
  },
  {
    experienceLevel: 'entry',
    firstName: 'Emeka',
    lastName: 'Nwosu',
    gender: 'male',
    dateOfBirth: '2002-05-30',
    phoneNumber: '+234 800 000 0004',
    location: 'Enugu, Enugu',
    jobTitle: 'Graduate Electrical Engineer',
    availability: 'immediate',
    education:
      'BEng Electrical/Electronic Engineering, University of Nigeria, Nsukka (2025), Second Class Lower. NYSC service completed 2026.',
    skills: ['AutoCAD', 'Circuit Design', 'MATLAB', 'Technical Drawing', 'Electrical Installation', 'Basic PLC Programming'],
    certifications: ['AutoCAD Certified User (Autodesk)', 'Basic Occupational Health & Safety Certificate'],
    workExperience:
      'Completed a six-month industrial training placement with an electrical contractor in Enugu, assisting with low-voltage installation drawings, site surveys and load calculations for commercial buildings. Final-year project: an automatic power-changeover system with load monitoring, built and demonstrated on a working prototype.',
  },
  {
    experienceLevel: 'entry',
    status: 'submitted',
    firstName: 'Ngozi',
    lastName: 'Eze',
    gender: 'female',
    dateOfBirth: '2003-01-19',
    phoneNumber: '+234 800 000 0005',
    location: 'Owerri, Imo',
    jobTitle: 'Customer Service Assistant',
    availability: 'immediate',
    education: 'HND Business Administration, Federal Polytechnic Nekede (2025), Upper Credit. NYSC service completed 2026.',
    skills: ['Customer Service', 'Data Entry', 'Microsoft Office', 'Front Desk Administration', 'Complaint Resolution'],
    certifications: ['Google Digital Skills for Africa', 'Customer Service Fundamentals (Alison)'],
    workExperience:
      'Served as a customer-service assistant during my NYSC year at a microfinance bank, handling account enquiries, logging complaints in the ticketing system and resolving routine issues within the same day. Previously interned at a retail store, managing stock records and daily sales entry.',
  },

  {
    experienceLevel: 'junior',
    firstName: 'Oluwaseun',
    lastName: 'Adeyemi',
    gender: 'prefer_not_to_say',
    dateOfBirth: '2000-06-09',
    phoneNumber: '+234 800 000 0006',
    location: 'Lekki, Lagos',
    jobTitle: 'Data Analyst',
    availability: 'two_weeks',
    education: 'BSc Statistics, Obafemi Awolowo University (2022), Second Class Upper.',
    skills: ['SQL', 'Power BI', 'Python', 'Data Analysis', 'Microsoft Excel', 'Data Visualisation', 'Statistics'],
    certifications: [
      'Microsoft Certified: Power BI Data Analyst Associate (PL-300)',
      'Google Data Analytics Professional Certificate',
    ],
    workExperience:
      'Over two years as a data analyst at a Lagos fintech, building Power BI dashboards for the lending and collections teams and writing SQL to track loan performance. Automated a weekly reporting pack that previously took two analysts a full day, cutting it to under an hour. Before that, an NYSC year supporting a state statistics office with survey data cleaning.',
  },
  {
    experienceLevel: 'junior',
    firstName: 'Blessing',
    lastName: 'Udoh',
    gender: 'female',
    dateOfBirth: '1999-12-05',
    phoneNumber: '+234 800 000 0007',
    location: 'Port Harcourt, Rivers',
    jobTitle: 'HR Officer',
    availability: 'one_month',
    education: 'BSc Human Resource Management, University of Port Harcourt (2022), Second Class Upper.',
    skills: ['Recruitment', 'HR Administration', 'Onboarding', 'Payroll Support', 'Employee Relations', 'HRIS', 'Interview Coordination'],
    certifications: ['CIPM Nigeria — Associate Member', 'HR Analytics Fundamentals (LinkedIn Learning)'],
    workExperience:
      'Two and a half years in HR at an oil-services company in Port Harcourt: coordinated recruitment for 40+ field and office hires, ran new-joiner onboarding, and maintained employee records in the HRIS. Supported monthly payroll validation and handled first-line employee queries on leave and benefits.',
  },
  {
    experienceLevel: 'junior',
    firstName: 'Ibrahim',
    lastName: 'Musa',
    gender: 'male',
    dateOfBirth: '2000-02-17',
    phoneNumber: '+234 800 000 0008',
    location: 'Kaduna, Kaduna',
    jobTitle: 'Sales Executive',
    availability: 'immediate',
    education: 'BSc Business Administration, Ahmadu Bello University Zaria (2022), Second Class Lower.',
    skills: ['B2B Sales', 'CRM (HubSpot)', 'Lead Generation', 'Negotiation', 'Sales Reporting', 'Client Relationship Management'],
    certifications: ['HubSpot Sales Software Certification', 'Professional Selling Skills Workshop'],
    workExperience:
      'Two years as a sales executive for a Kaduna agro-inputs distributor, growing my territory\'s monthly revenue by roughly 35% through cold outreach and repeat-order programmes with farmer cooperatives. Maintained the pipeline in HubSpot and prepared weekly sales reports for the regional manager.',
  },
  {
    experienceLevel: 'junior',
    firstName: 'Folake',
    lastName: 'Adebayo',
    gender: 'female',
    dateOfBirth: '1999-09-25',
    phoneNumber: '+234 800 000 0009',
    location: 'Abeokuta, Ogun',
    jobTitle: 'Product Designer',
    availability: 'two_weeks',
    education: 'BSc Computer Engineering, Federal University of Agriculture, Abeokuta (2022), Second Class Upper.',
    skills: ['UI/UX Design', 'Figma', 'Prototyping', 'User Research', 'Wireframing', 'Design Systems', 'Usability Testing'],
    certifications: ['Google UX Design Professional Certificate', 'Interaction Design Foundation — UI Design Patterns'],
    workExperience:
      'Product designer for two years at a health-tech start-up, owning the redesign of its patient-booking flow, which lifted completed bookings by 22%. Ran moderated usability sessions with clinic staff, built a shared Figma component library and worked in a two-week sprint cadence with three engineers.',
  },
  {
    experienceLevel: 'junior',
    status: 'submitted',
    firstName: 'Chukwuemeka',
    lastName: 'Obi',
    gender: 'male',
    dateOfBirth: '1998-07-11',
    phoneNumber: '+234 800 000 0010',
    location: 'Benin City, Edo',
    jobTitle: 'Site Engineer',
    availability: 'immediate',
    education: 'BEng Civil Engineering, University of Benin (2022), Second Class Upper.',
    skills: ['Site Supervision', 'AutoCAD', 'Quantity Surveying', 'Project Scheduling', 'Concrete Works QA', 'Health & Safety Compliance'],
    certifications: ['COREN Graduate Registration', 'Working at Heights Safety Certificate'],
    workExperience:
      'Three years as a site engineer on residential and light-commercial projects in Benin City, supervising subcontractors, checking concrete and reinforcement quality, and keeping daily progress logs. Prepared bills of quantities for two projects under a senior quantity surveyor and tracked site materials against the programme.',
  },

  {
    experienceLevel: 'mid',
    firstName: 'Amaka',
    lastName: 'Onyeama',
    gender: 'female',
    dateOfBirth: '1994-04-03',
    phoneNumber: '+234 800 000 0011',
    location: 'Ikeja, Lagos',
    jobTitle: 'Marketing Manager',
    availability: 'one_month',
    education: 'MSc Marketing, University of Lagos (2019). BSc Business Administration, University of Nigeria, Nsukka (2016).',
    skills: [
      'Digital Marketing',
      'SEO',
      'Google Analytics',
      'Brand Strategy',
      'Campaign Management',
      'Paid Media',
      'Marketing Analytics',
      'Team Management',
    ],
    certifications: [
      'Google Analytics Individual Qualification',
      'HubSpot Inbound Marketing Certification',
      'Meta Certified Digital Marketing Associate',
    ],
    workExperience:
      'Six years in marketing, most recently as Marketing Manager at a consumer-goods company in Ikeja, where I led a team of four and managed an annual digital budget of about ₦45 million. Repositioned the flagship brand\'s paid and organic channels, increasing qualified leads by 60% year on year. Earlier roles covered SEO and email marketing at a digital agency.',
  },
  {
    experienceLevel: 'mid',
    firstName: 'Yusuf',
    lastName: 'Danjuma',
    gender: 'male',
    dateOfBirth: '1993-10-28',
    phoneNumber: '+234 800 000 0012',
    location: 'Wuse 2, Abuja',
    jobTitle: 'Backend Engineer',
    availability: 'two_weeks',
    education: 'BSc Software Engineering, Ahmadu Bello University Zaria (2015). MSc Computer Science, University of Abuja (2019).',
    skills: ['Node.js', 'TypeScript', 'PostgreSQL', 'REST API Design', 'Docker', 'AWS', 'Microservices', 'CI/CD', 'MongoDB'],
    certifications: ['AWS Certified Developer – Associate', 'Certified Kubernetes Application Developer (CKAD)'],
    workExperience:
      'Six years as a backend engineer, the last three at an Abuja payments company where I own the transaction-reconciliation service processing about 200,000 records a day. Led the migration of a monolith\'s billing module to containerised services on AWS, reducing deployment time from hours to minutes. Mentor two junior developers and run the team\'s code-review practice.',
  },
  {
    experienceLevel: 'mid',
    firstName: 'Temitope',
    lastName: 'Ogunleye',
    gender: 'female',
    dateOfBirth: '1995-01-22',
    phoneNumber: '+234 800 000 0013',
    location: 'Victoria Island, Lagos',
    jobTitle: 'Finance Manager',
    availability: 'one_month',
    education: 'BSc Accounting, Covenant University (2018), First Class. Associate Chartered Accountant (ACA), ICAN (2022).',
    skills: ['Financial Reporting', 'IFRS', 'External Audit', 'Tax Compliance', 'Budgeting & Forecasting', 'Month-End Close', 'SAP FI'],
    certifications: ['ACA — Institute of Chartered Accountants of Nigeria', 'ACCA Diploma in IFRS'],
    workExperience:
      'Seven years in accounting and audit: three years at a mid-sized audit firm across banking and manufacturing clients, then four years as Finance Manager at a logistics company, where I run the month-end close, statutory reporting and the annual budget. Introduced a reconciliation checklist that cut close time from ten working days to six.',
  },
  {
    experienceLevel: 'mid',
    firstName: 'Nnamdi',
    lastName: 'Chukwu',
    gender: 'male',
    dateOfBirth: '1994-08-15',
    phoneNumber: '+234 800 000 0014',
    location: 'Enugu, Enugu',
    jobTitle: 'Maintenance Planner',
    availability: 'not_available',
    education: 'BEng Mechanical Engineering, Enugu State University of Science and Technology (2018).',
    skills: ['Maintenance Planning', 'Lean Manufacturing', 'Quality Assurance', 'Root Cause Analysis', 'AutoCAD', 'Six Sigma', 'Preventive Maintenance'],
    certifications: ['Six Sigma Green Belt', 'COREN Registered Engineer'],
    workExperience:
      'Six years in plant engineering for a beverage manufacturer, progressing from maintenance engineer to maintenance planner. Built the preventive-maintenance schedule for the bottling line, cutting unplanned downtime by 28%, and led a Six Sigma project that reduced fill-volume rejects by a third.',
  },
  {
    experienceLevel: 'mid',
    status: 'under_review',
    firstName: 'Halima',
    lastName: 'Sani',
    gender: 'female',
    dateOfBirth: '1993-12-09',
    phoneNumber: '+234 800 000 0015',
    location: 'Gwarinpa, Abuja',
    jobTitle: 'Project Coordinator',
    availability: 'two_weeks',
    education: 'BSc Public Administration, Bayero University Kano (2016).',
    skills: ['Project Management', 'Stakeholder Management', 'Agile & Scrum', 'MS Project', 'Risk Tracking', 'Budget Tracking', 'Reporting'],
    certifications: ['PRINCE2 Foundation', 'Professional Scrum Master I (PSM I)'],
    workExperience:
      'Five years coordinating projects for a development consultancy and then a telecoms operator in Abuja. Currently Project Coordinator on a fibre roll-out programme with a ₦1.2 billion budget, tracking milestones across eight workstreams, chasing risks and producing the fortnightly steering-committee pack.',
  },

  {
    experienceLevel: 'senior',
    firstName: 'Adebayo',
    lastName: 'Ogunbanjo',
    gender: 'male',
    dateOfBirth: '1985-03-07',
    phoneNumber: '+234 800 000 0016',
    location: 'Ikoyi, Lagos',
    jobTitle: 'Head of Operations',
    availability: 'one_month',
    education: 'MBA, Lagos Business School (2016). BSc Business Administration, University of Lagos (2007).',
    skills: [
      'Strategic Planning',
      'P&L Management',
      'Operations Leadership',
      'Business Development',
      'Stakeholder Management',
      'Process Improvement',
      'Budgeting',
      'Team Leadership',
    ],
    certifications: ['Project Management Professional (PMP)', 'Lean Six Sigma Black Belt'],
    workExperience:
      'Nineteen years in the workforce, fifteen of them in operations leadership across FMCG and logistics. Currently Head of Operations at a national distribution business, accountable for a ₦18 billion P&L, six depots and a team of 240. Restructured the depot network to cut delivery lead time by 30%, and previously led the launch of two regional hubs from feasibility to first shipment.',
  },
  {
    experienceLevel: 'senior',
    firstName: 'Ifeoma',
    lastName: 'Nwankwo',
    gender: 'female',
    dateOfBirth: '1987-06-18',
    phoneNumber: '+234 800 000 0017',
    location: 'Lekki, Lagos',
    jobTitle: 'Engineering Manager',
    availability: 'two_weeks',
    education: 'MSc Information Systems, University of Lagos (2013). BSc Computer Science, University of Nigeria, Nsukka (2009).',
    skills: [
      'Software Architecture',
      'Engineering Management',
      'Cloud Infrastructure',
      'System Design',
      'Agile Delivery',
      'Technical Hiring',
      'Node.js',
      'Kubernetes',
      'Security Practices',
    ],
    certifications: ['AWS Certified Solutions Architect – Professional', 'Certified ScrumMaster (CSM)'],
    workExperience:
      'Seventeen years in software, the last six in engineering management. As Engineering Manager at a Lagos fintech I lead 22 engineers across four squads, own the platform roadmap, and set architecture standards for services handling millions of transactions monthly. Reduced production incidents by 45% through an on-call and post-incident review programme, and grew two tech leads into principal-level roles.',
  },
  {
    experienceLevel: 'senior',
    firstName: 'Mohammed',
    lastName: 'Abdullahi',
    gender: 'male',
    dateOfBirth: '1984-09-30',
    phoneNumber: '+234 800 000 0018',
    location: 'Maitama, Abuja',
    jobTitle: 'Finance Director',
    availability: 'not_available',
    education: 'MSc Finance, University of Abuja (2012). BSc Accounting, Ahmadu Bello University Zaria (2006).',
    skills: [
      'Financial Strategy',
      'Treasury Management',
      'IFRS',
      'Risk Management',
      'Fundraising',
      'Financial Modelling',
      'Investor Relations',
      'Board Reporting',
    ],
    certifications: ['ACA — Institute of Chartered Accountants of Nigeria', 'CFA Level III Candidate'],
    workExperience:
      'Twenty years in finance. Currently Finance Director of an Abuja-based infrastructure group, responsible for treasury, statutory reporting and lender relationships. Led a ₦12 billion debt refinancing, built the group\'s five-year financial model, and present monthly performance to the board and audit committee.',
  },
  {
    experienceLevel: 'senior',
    status: 'submitted',
    firstName: 'Grace',
    lastName: 'Ekpo',
    gender: 'female',
    dateOfBirth: '1988-02-11',
    phoneNumber: '+234 800 000 0019',
    location: 'Uyo, Akwa Ibom',
    jobTitle: 'HR Director',
    availability: 'one_month',
    education: 'MSc Industrial Relations and Personnel Management, University of Lagos (2014). BA Sociology, University of Calabar (2009).',
    skills: [
      'Talent Strategy',
      'Organisational Development',
      'Employment Law',
      'Compensation & Benefits',
      'Change Management',
      'Workforce Planning',
      'Leadership Coaching',
      'HR Business Partnering',
    ],
    certifications: [
      'Fellow, Chartered Institute of Personnel Management of Nigeria (CIPM)',
      'SHRM Senior Certified Professional (SHRM-SCP)',
    ],
    workExperience:
      'Seventeen years in HR across oil-and-gas services and banking. Currently HR Director for a 900-person company, reporting to the CEO: designed the grading and reward framework, led a restructuring that moved 120 roles with no litigation, and cut voluntary attrition from 19% to 11% in two years. Sit on the executive committee and coach the leadership team.',
  },
  {
    experienceLevel: 'senior',
    firstName: 'Olumide',
    lastName: 'Fashola',
    gender: 'male',
    dateOfBirth: '1986-11-24',
    phoneNumber: '+234 800 000 0020',
    location: 'Victoria Island, Lagos',
    jobTitle: 'Projects Director',
    availability: 'immediate',
    education: 'MSc Construction Management, University of Lagos (2014). BSc Civil Engineering, Obafemi Awolowo University (2008).',
    skills: [
      'Construction Management',
      'Contract Administration',
      'Cost Control',
      'Risk Management',
      'Stakeholder Management',
      'Programme Planning',
      'Procurement',
      'Team Leadership',
    ],
    certifications: [
      'Project Management Professional (PMP)',
      'COREN Registered Engineer',
      'FIDIC Contract Management Certificate',
    ],
    workExperience:
      'Eighteen years in construction. Currently Projects Director at a Lagos developer, overseeing a portfolio of six residential and mixed-use sites worth ₦40 billion. Deliver projects through contractor procurement, FIDIC contract administration and monthly cost-to-complete reviews; brought the last two towers in ahead of programme and within 2% of budget.',
  },
]);
